import type { ChipId } from '../../data/chips';

// 16×16 pixel icons for chip faces (TERMINAL.md §6.1, style guide §6).
// Original designs; '.' is transparent, other characters map to ICON_PALETTE.

export const ICON_PALETTE: Record<string, string> = {
  k: '#141414',
  w: '#f2f2e8',
  g: '#9aa0a6',
  d: '#4a4f55',
  y: '#ffd166',
  o: '#ff8a3d',
  r: '#e04040',
  b: '#5f86ff',
  c: '#9fe8ff',
  G: '#3fcf6a',
  l: '#b8ffb0',
  p: '#7a4fd0',
};

export const CHIP_ICONS: Record<ChipId, readonly string[]> = {
  cannon: [
    '................',
    '......kkkk......',
    '......kcck......',
    '......kbbk......',
    '......kbbk......',
    '......kbbk......',
    '......kbbk......',
    '.....kkbbkk.....',
    '....kggbbggk....',
    '...kggggggggk...',
    '...kgddggddgk...',
    '...kgddggddgk...',
    '...kggggggggk...',
    '....kkkkkkkk....',
    '....kdk..kdk....',
    '....kkk..kkk....',
  ],
  hicannon: [
    '................',
    '.....kkkkkk.....',
    '.....kcwwck.....',
    '.....kbbbbk.....',
    '.....krrrrk.....',
    '.....kbbbbk.....',
    '.....kbbbbk.....',
    '....kkbbbbkk....',
    '...kggbbbbggk...',
    '..kggggggggggk..',
    '..kgddggggddgk..',
    '..kgddggggddgk..',
    '..kggggggggggk..',
    '...kkkkkkkkkk...',
    '...kdk....kdk...',
    '...kkk....kkk...',
  ],
  sword: [
    '................',
    '............kkk.',
    '...........kwwk.',
    '..........kwwk..',
    '.........kwwk...',
    '........kwwk....',
    '.......kwwk.....',
    '......kwwk......',
    '..kk.kwwk.......',
    '..kykkwk........',
    '...kyyk.........',
    '...kkyyk........',
    '..kook.kk.......',
    '.kook...........',
    '.kkk............',
    '................',
  ],
  widesword: [
    '................',
    '..kkkkkkkkkkkk..',
    '.kwwwwwwwwwwwwk.',
    '.kwggggggggggwk.',
    '..kwwwwwwwwwwk..',
    '...kkkkkkkkkk...',
    '.......kk.......',
    '......kyyk......',
    '.....kyyyyk.....',
    '......kyyk......',
    '......kook......',
    '......kook......',
    '......kook......',
    '......kyyk......',
    '.......kk.......',
    '................',
  ],
  longsword: [
    '.......kk.......',
    '......kwwk......',
    '......kwwk......',
    '......kwgk......',
    '......kwgk......',
    '......kwgk......',
    '......kwgk......',
    '......kwgk......',
    '......kwgk......',
    '....kkkyykkk....',
    '....kyyyyyyk....',
    '....kkkookkk....',
    '......kook......',
    '......kook......',
    '......kyyk......',
    '.......kk.......',
  ],
  shotgun: [
    '................',
    '...o...o...o....',
    '....o..o..o.....',
    '.....kkkkkk.....',
    '.....kbkkbk.....',
    '.....kbkkbk.....',
    '.....kbkkbk.....',
    '.....kbkkbk.....',
    '....kkbkkbkk....',
    '...kggggggggk...',
    '...kgddggddgk...',
    '...kggggggggk...',
    '....kkkkkkkk....',
    '....kok..kok....',
    '....kkk..kkk....',
    '................',
  ],
  minibomb: [
    '................',
    '..........o.....',
    '.........oyo....',
    '..........k.....',
    '.........k......',
    '......kkkk......',
    '....kkppppkk....',
    '...kppwppppk....',
    '...kpwppppppk...',
    '..kppppppppppk..',
    '..kppppppppppk..',
    '..kppppppppppk..',
    '...kppppppppk...',
    '...kppppppppk...',
    '....kkppppkk....',
    '......kkkk......',
  ],
  recover50: [
    '................',
    '......kkkk......',
    '......kGGk......',
    '......kGGk......',
    '......kGGk......',
    '..kkkkkGGkkkkk..',
    '..kGGGGllGGGGk..',
    '..kGGGGllGGGGk..',
    '..kkkkkGGkkkkk..',
    '......kGGk......',
    '......kGGk......',
    '......kGGk......',
    '......kkkk......',
    '................',
    '................',
    '................',
  ],
};
