import type { ChipId } from '../../data/chips';

// 16×16 pixel icons for chip faces (TERMINAL.md §6.1, style guide §6).
// Original designs; '.' is transparent, other characters map to ICON_PALETTE.

export const ICON_PALETTE: Record<string, string> = {
  k: '#141414',
  w: '#f2f2e8',
  g: '#9aa0a6',
  d: '#4a4f55',
  y: '#ffd166',
  o: '#ff8a3d',
  r: '#e04040',
  b: '#5f86ff',
  c: '#9fe8ff',
  G: '#3fcf6a',
  l: '#b8ffb0',
  p: '#7a4fd0',
};

const BASE_ICONS = {
  cannon: [
    '................',
    '......kkkk......',
    '......kcck......',
    '......kbbk......',
    '......kbbk......',
    '......kbbk......',
    '......kbbk......',
    '.....kkbbkk.....',
    '....kggbbggk....',
    '...kggggggggk...',
    '...kgddggddgk...',
    '...kgddggddgk...',
    '...kggggggggk...',
    '....kkkkkkkk....',
    '....kdk..kdk....',
    '....kkk..kkk....',
  ],
  hicannon: [
    '................',
    '.....kkkkkk.....',
    '.....kcwwck.....',
    '.....kbbbbk.....',
    '.....krrrrk.....',
    '.....kbbbbk.....',
    '.....kbbbbk.....',
    '....kkbbbbkk....',
    '...kggbbbbggk...',
    '..kggggggggggk..',
    '..kgddggggddgk..',
    '..kgddggggddgk..',
    '..kggggggggggk..',
    '...kkkkkkkkkk...',
    '...kdk....kdk...',
    '...kkk....kkk...',
  ],
  sword: [
    '................',
    '............kkk.',
    '...........kwwk.',
    '..........kwwk..',
    '.........kwwk...',
    '........kwwk....',
    '.......kwwk.....',
    '......kwwk......',
    '..kk.kwwk.......',
    '..kykkwk........',
    '...kyyk.........',
    '...kkyyk........',
    '..kook.kk.......',
    '.kook...........',
    '.kkk............',
    '................',
  ],
  widesword: [
    '................',
    '..kkkkkkkkkkkk..',
    '.kwwwwwwwwwwwwk.',
    '.kwggggggggggwk.',
    '..kwwwwwwwwwwk..',
    '...kkkkkkkkkk...',
    '.......kk.......',
    '......kyyk......',
    '.....kyyyyk.....',
    '......kyyk......',
    '......kook......',
    '......kook......',
    '......kook......',
    '......kyyk......',
    '.......kk.......',
    '................',
  ],
  longsword: [
    '.......kk.......',
    '......kwwk......',
    '......kwwk......',
    '......kwgk......',
    '......kwgk......',
    '......kwgk......',
    '......kwgk......',
    '......kwgk......',
    '......kwgk......',
    '....kkkyykkk....',
    '....kyyyyyyk....',
    '....kkkookkk....',
    '......kook......',
    '......kook......',
    '......kyyk......',
    '.......kk.......',
  ],
  shotgun: [
    '................',
    '...o...o...o....',
    '....o..o..o.....',
    '.....kkkkkk.....',
    '.....kbkkbk.....',
    '.....kbkkbk.....',
    '.....kbkkbk.....',
    '.....kbkkbk.....',
    '....kkbkkbkk....',
    '...kggggggggk...',
    '...kgddggddgk...',
    '...kggggggggk...',
    '....kkkkkkkk....',
    '....kok..kok....',
    '....kkk..kkk....',
    '................',
  ],
  minibomb: [
    '................',
    '..........o.....',
    '.........oyo....',
    '..........k.....',
    '.........k......',
    '......kkkk......',
    '....kkppppkk....',
    '...kppwppppk....',
    '...kpwppppppk...',
    '..kppppppppppk..',
    '..kppppppppppk..',
    '..kppppppppppk..',
    '...kppppppppk...',
    '...kppppppppk...',
    '....kkppppkk....',
    '......kkkk......',
  ],
  recover50: [
    '................',
    '......kkkk......',
    '......kGGk......',
    '......kGGk......',
    '......kGGk......',
    '..kkkkkGGkkkkk..',
    '..kGGGGllGGGGk..',
    '..kGGGGllGGGGk..',
    '..kkkkkGGkkkkk..',
    '......kGGk......',
    '......kGGk......',
    '......kGGk......',
    '......kkkk......',
    '................',
    '................',
    '................',
  ],
} satisfies Record<string, readonly string[]>;

const NEW_ICONS = {
  vulcan: [
    '................',
    '....kkkkkkkk....',
    '...kcccccccck...',
    '..kbbbbbbbbbbk..',
    '..kbbkkkkkbbbk..',
    '..kbbk...kbbbk..',
    '..kbbkkkkkbbbk..',
    '..kbbbbbbbbbbk..',
    '...kkkkbbbbkk...',
    '......kbbbbk....',
    '......kbbbbk....',
    '.....kkggggkk...',
    '....kggggggggk..',
    '....kgddggddgk..',
    '.....kkkkkkkk...',
    '................',
  ],
  barrier: [
    '................',
    '......kkkk......',
    '....kkcccckk....',
    '...kccbbbbcck...',
    '..kccbbbbbbcck..',
    '..kcbbbbbbbbck..',
    '..kcbbbbbbbbck..',
    '..kcbbbbbbbbck..',
    '..kcbbbbbbbbck..',
    '...kcbbbbbbck...',
    '...kccbbbbcck...',
    '....kccbbcck....',
    '.....kcccck.....',
    '......kcck......',
    '.......kk.......',
    '................',
  ],
  wave: [
    '................',
    '................',
    '................',
    '.......cc.......',
    '......cbbc......',
    '.....cb..bc.....',
    '....cb....bc....',
    '...cb.cc...bc...',
    '..cb.cbbc...bc..',
    '.cb.cb..bc...bc.',
    'cb.cb....bc...bc',
    'b.cb......bc...b',
    '.cb........bc...',
    'kkkkkkkkkkkkkkkk',
    'dddddddddddddddd',
    '................',
  ],
  zap: [
    '..........yyyy..',
    '.........yyyk...',
    '........yyyk....',
    '.......yyyk.....',
    '......yyyk......',
    '.....yyyk.......',
    '....yyyyyyyyy...',
    '.....kkkyyyk....',
    '.......yyyk.....',
    '......yyyk......',
    '.....yyk........',
    '....yyk.........',
    '...yk...........',
    '..yk............',
    '.y..............',
    '................',
  ],
  invis: [
    '................',
    '.......c........',
    '......c.c.......',
    '.....c...c......',
    '......c.c.......',
    '................',
    '....c.c.c.c.....',
    '...c.......c....',
    '..c..c...c..c...',
    '.....c...c......',
    '....c.....c.....',
    '.....c...c......',
    '....c.....c.....',
    '...c.......c....',
    '..cc.......cc...',
    '................',
  ],
  crack: [
    'kkkkkkkkkkkkkkkk',
    'kbbbbbbwbbbbbbbk',
    'kbbbbbbwbbbbbbbk',
    'kbbbbbwwbbbbbbbk',
    'kbbbbbwbbbbbbbbk',
    'kbbbbbbwwbbbbbbk',
    'kbbbbbbbwbbbbbbk',
    'kbbbbbbwwbbbbbbk',
    'kbbbbbwwbbbbbbbk',
    'kbbbbwwbbbwbbbbk',
    'kbbbbwbbbwwbbbbk',
    'kbbbbwwwwwbbbbbk',
    'kbbbbbbbbbbbbbbk',
    'kbbbbbbbbbbbbbbk',
    'kkkkkkkkkkkkkkkk',
    '.dddddddddddddd.',
  ],
  rock: [
    '................',
    '................',
    '.....kkkkkk.....',
    '....kggggggk....',
    '...kgwggggdgk...',
    '..kgwgggggddgk..',
    '..kggggggggdgk..',
    '..kgggdggggggk..',
    '..kggddgggggdk..',
    '..kgggggggddgk..',
    '..kdgggggdddgk..',
    '...kddddddddk...',
    '....kkkkkkkk....',
    '................',
    '................',
    '................',
  ],
  steal: [
    '................',
    '..rrrrrrrrrrrr..',
    '..rkkkkkkkkkkr..',
    '..rrrrrrrrrrrr..',
    '.......cc.......',
    '......cccc......',
    '.....cccccc.....',
    '....cccccccc....',
    '.......cc.......',
    '.......cc.......',
    '.......cc.......',
    '..bbbbbbbbbbbb..',
    '..bkkkkkkkkkkb..',
    '..bbbbbbbbbbbb..',
    '................',
    '................',
  ],
  repair: [
    '................',
    '..........GGG...',
    '.........G...G..',
    '.........G..GG..',
    '..........G..GG.',
    '.........G....G.',
    '........G..GGG..',
    '.......G..G.....',
    '......G..G......',
    '.....G..G.......',
    '....G..G........',
    '...G..G.........',
    '..G..G..........',
    '..G.G...........',
    '...G............',
    '................',
  ],
} satisfies Record<string, readonly string[]>;

const B = BASE_ICONS;
const N = NEW_ICONS;

/** Every chip's icon; new chips reuse the closest family icon where one fits. */
export const CHIP_ICONS: Record<ChipId, readonly string[]> = {
  ...B,
  vulcan: N.vulcan,
  mcannon: B.hicannon,
  airshot: B.cannon,
  vgun: B.shotgun,
  sidegun: B.shotgun,
  spreader: B.shotgun,
  shockwave: N.wave,
  zapring: N.zap,
  recov10: B.recover50,
  recov30: B.recover50,
  recov80: B.recover50,
  invis: N.invis,
  barrier: N.barrier,
  geddon1: N.crack,
  geddon2: N.crack,
  areagrab: N.steal,
  panlgrab: N.steal,
  panlout1: N.crack,
  panlout3: N.crack,
  repair: N.repair,
  rockcube: N.rock,
};
